language:
  - ruby
addons:
  postgresql: '9.5'
  apt:
    sources:
      - sourceline: 'deb http://repo.zabbix.com/zabbix/3.0/ubuntu/ trusty main'
        key_url: 'http://repo.zabbix.com/zabbix-official-repo.key'
    packages:
      - php5-pgsql
      - zabbix-frontend-php
      - zabbix-server-pgsql
services:
  - postgresql
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
gemfile:
  - Gemfile
  - json-1.x.Gemfile
dist: trusty
sudo: required

before_script:
  - sudo sed -i "s,;date.timezone =,date.timezone = 'US/Eastern'," /etc/php5/apache2/php.ini
  - psql -c 'create database zabbix;' -U postgres
  - psql -c 'create user zabbix;' -U postgres
  - psql -c 'grant all privileges on database zabbix to zabbix;' -U postgres
  - zcat /usr/share/doc/zabbix-server-pgsql/create.sql.gz | LC_ALL=C psql -U zabbix
  - echo "$(curl -fsSL https://gist.githubusercontent.com/evtuhovich/9544441/raw/d661863063b76cc8e2599bc44d8595b1f86ece38/zabbix)" | sudo tee /etc/zabbix/web/zabbix.conf.php
  - sudo service apache2 restart
script: "ZABBIX_HOST_URL=http://localhost/zabbix/api_jsonrpc.php bundle exec rspec spec/*"

matrix:
  exclude:
    # json 2.x requires ruby 2.x
    - rvm: 1.9.3
      gemfile: json-1.x.Gemfile
